### ISSUE TITLE
Chrome Extensions Link 404?

### ISSUE THREAD

**Issue by gallak87** [SafetyCulture/grpc-web-devtools#106]
Clicking the link from the readme takes me to a 404. Is this extension still working? Is there a newer link somewhere?

**Comment by btipling** [comment]
It was removed because Google marked it as unsafe

![image](https://user-images.githubusercontent.com/249641/134855470-a194f417-1870-4c43-8550-def96a9aa475.png)

**Comment by TomWright** [comment]
Does anyone know of a viable alternative?

**Comment by infodusha** [comment]
I guess that is ralted to https://github.com/reduxjs/redux-devtools/issues/713
My proposial for now is that "activeTab" permission not used. Who can handle that?

**Comment by kostyay** [comment]
any progress on this? 
we use this plugin a lot.

**Comment by kinotto** [comment]
same here, the plugin doesn't work properly anymore, can't find an alternative in the chrome web store

**Comment by TomWright** [comment]
If you had the plugin installed prior to it disappearing you can enable it manually here: chrome://extensions/

![image](https://user-images.githubusercontent.com/935867/135263328-161b5906-d0da-462c-b26c-1053926cfe6a.png)

**Comment by georgechieng-sc** [comment]
Hi all 👋 
We are currently in the process of establishing a dedicated working group to revive and maintain this dev tool. Please wait patiently as we get set up.

**Comment by lukedukeus** [comment]
@georgechieng-sc The link is broken again :(
