### ISSUE TITLE
grpc-web-devtools will not work for streaming calls if the client chain the streaming callbacks.

### ISSUE THREAD

**Issue by kitchenSpoon** [SafetyCulture/grpc-web-devtools#28]
Tested on commit: https://github.com/SafetyCulture/grpc-web-devtools/commit/9d78d6238477399da010d4466db8a916ac421d56

Seems like the streaming callback for "status" is not being call when using the build of grpc-web-devtools with the above commit.

**Comment by rogchap** [comment]
Can you provide more info on what is not working? I can't reproduce issues with the `status` callbacks.

**Comment by kitchenSpoon** [comment]
I have code similar to this which chain the callbacks
```
this.client.getStreamingResponse()
  .on("data", response => {})
  .on("status", status => {})
```
which does not work for the callbacks after the first.

but this will work

```
const response = this.client.getStreamingResponse()
response.on("data", response => {})
response.on("status", status => {})
```
