### ISSUE TITLE
Cannot read property 'rpcCall' of undefined

### ISSUE THREAD

**Issue by smazurov** [SafetyCulture/grpc-web-devtools#33]
Injector doesn't work and fails with:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'rpcCall' of undefined
TypeError: Cannot read property 'rpcCall' of undefined
    at inject.js:62
    at Array.map (<anonymous>)
    at window.__GRPCWEB_DEVTOOLS__ (inject.js:61)
    at new MyFunction (myFunction.ts:24)
    .......
```

I suspect it comes down to how I generate grpc-web client:

```
protoc \
  --js_out=import_style=typescript:$OUT_DIR \
  --grpc-web_out=import_style=commonjs,mode=grpcwebtext:$OUT_DIR ${FILE}
```

**Comment by iCovarrubias** [comment]
Same here, @smazurov , are you using the `PromisedClient` ? For me it works if I use the regular client, e.g.:


**This works:**
`const {GreeterClient} = require('./helloworld_grpc_web_pb.js');`

**This breaks with the same error:**
const {GreeterPromisedClient} = require('./helloworld_grpc_web_pb.js');


Still, I would prefer the extension to work with the promised client instead of the regular one.

**Comment by smazurov** [comment]
I was not. I am using same client as readme directions

**Comment by rogchap** [comment]
It works with `PromiseClient`, see the example.
What version of grpc-web are you using to generate the clients? The generator changed the implementation of the promise client. 
Can you try upgrading your `protoc-gen-grpc-web` plugin to the latest 1.0.4 release.

**Comment by nielskrijger** [comment]
I was having the exact same error using the promise client. After upgrading `protoc-gen-grpc-web` to 1.0.4 it worked fine.

We could add a notice in the readme that the minimal supported version is 1.0.4.

**Comment by iCovarrubias** [comment]
> Can you try upgrading your protoc-gen-grpc-web plugin to the latest 1.0.4 release.

Worked for me after doing this one.

**Comment by rogchap** [comment]
Great, I'm glad you were able to get this working. 
Will add a note to the README so it's clear that you need 1.0.4
