### ISSUE TITLE
__GRPCWEB_DEVTOOLS__ not injected into all frames

### ISSUE THREAD

**Issue by jackielii** [SafetyCulture/grpc-web-devtools#42]
probably need `"all_frames": true` in the manifest.json

**Comment by jackielii** [comment]
I'm using storybook, although even after this, I still need to use a setTimeout, because the app js is executed first, then the content script is injected...

**Comment by rogchap** [comment]
Hey @jackielii thanks for this. 
Why is the content script injected **after** your app js? 
I'm sure it's meant to be injected first.

**Comment by jackielii** [comment]
No idea. It appears that way most of the time. I'm puzzled by this as I see all other plugins injected the scripts successfully... Could it be other permissions?
