### ISSUE TITLE
Enable clipboard when viewing the grpc details

### ISSUE THREAD

**Issue by kitchenSpoon** [SafetyCulture/grpc-web-devtools#49]
Currently when you're copy pasting the json view of the grpc response, it is not handled well.
<img width="945" alt="Screen Shot 2019-10-19 at 11 19 32 pm" src="https://user-images.githubusercontent.com/2775497/67144869-9bee2500-f2c7-11e9-97dd-45d443921fb5.png">
<img width="663" alt="Screen Shot 2019-10-19 at 11 19 46 pm" src="https://user-images.githubusercontent.com/2775497/67144871-9bee2500-f2c7-11e9-9146-f52d09902c61.png">

**Comment by rogchap** [comment]
Fixed in #56
