### ISSUE TITLE
Unavailable after update 1.2.0

### ISSUE THREAD

**Issue by helloaihao** [SafetyCulture/grpc-web-devtools#59]
There was no problem before, it will become like this after updating to 1.2.0 today.

<img width="519" alt="WX20191211-104257@2x" src="https://user-images.githubusercontent.com/13844306/70586854-3cdfc900-1c03-11ea-8b99-9f77925dd9bc.png">

**Comment by hotuy** [comment]
Me too, it's not working now...

**Comment by dinhtheloc** [comment]
i have same issue

**Comment by thdang1009** [comment]
the same to me

**Comment by darioielardi** [comment]
same here

**Comment by zeroarst** [comment]
same here..

**Comment by rogchap** [comment]
Damn... Looking now; as a workaround you can install the local version.

**Comment by rogchap** [comment]
This has been fixed (🤞) in v1.2.1.

It's been submitted to the stores: Chrome Store sadly takes a while to review (could be a day or two); Firefox is available now.

Sorry for the inconvenience everyone!
